
package dk.sst;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutRegService", targetNamespace = "http://sst.dk/", wsdlLocation = "http://autregwebservice.sst.dk/autregservice.asmx?WSDL")
public class AutRegService
    extends Service
{

    private final static URL AUTREGSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTREGSERVICE_EXCEPTION;
    private final static QName AUTREGSERVICE_QNAME = new QName("http://sst.dk/", "AutRegService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://autregwebservice.sst.dk/autregservice.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTREGSERVICE_WSDL_LOCATION = url;
        AUTREGSERVICE_EXCEPTION = e;
    }

    public AutRegService() {
        super(__getWsdlLocation(), AUTREGSERVICE_QNAME);
    }

    public AutRegService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTREGSERVICE_QNAME, features);
    }

    public AutRegService(URL wsdlLocation) {
        super(wsdlLocation, AUTREGSERVICE_QNAME);
    }

    public AutRegService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTREGSERVICE_QNAME, features);
    }

    public AutRegService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutRegService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutRegServiceSoap
     */
    @WebEndpoint(name = "AutRegServiceSoap")
    public AutRegServiceSoap getAutRegServiceSoap() {
        return super.getPort(new QName("http://sst.dk/", "AutRegServiceSoap"), AutRegServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutRegServiceSoap
     */
    @WebEndpoint(name = "AutRegServiceSoap")
    public AutRegServiceSoap getAutRegServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://sst.dk/", "AutRegServiceSoap"), AutRegServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTREGSERVICE_EXCEPTION!= null) {
            throw AUTREGSERVICE_EXCEPTION;
        }
        return AUTREGSERVICE_WSDL_LOCATION;
    }

}
