
package dk.sst;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutRegServiceSoap", targetNamespace = "http://sst.dk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutRegServiceSoap {


    /**
     * 
     * @param authorizationDateFrom
     * @param professionGroup
     * @param birthdayTo
     * @param specialityName
     * @param authorizationID
     * @param name
     * @param birthdayFrom
     * @param authorizationDateTo
     * @param seventyFiveYearsRule
     * @param authorizationStatus
     * @return
     *     returns dk.sst.ArrayOfHealthProfessional
     */
    @WebMethod(operationName = "GetHealthProfessionals", action = "http://sst.dk/GetHealthProfessionals")
    @WebResult(name = "GetHealthProfessionalsResult", targetNamespace = "http://sst.dk/")
    @RequestWrapper(localName = "GetHealthProfessionals", targetNamespace = "http://sst.dk/", className = "dk.sst.GetHealthProfessionals")
    @ResponseWrapper(localName = "GetHealthProfessionalsResponse", targetNamespace = "http://sst.dk/", className = "dk.sst.GetHealthProfessionalsResponse")
    public ArrayOfHealthProfessional getHealthProfessionals(
        @WebParam(name = "name", targetNamespace = "http://sst.dk/")
        String name,
        @WebParam(name = "authorizationID", targetNamespace = "http://sst.dk/")
        String authorizationID,
        @WebParam(name = "birthdayFrom", targetNamespace = "http://sst.dk/")
        XMLGregorianCalendar birthdayFrom,
        @WebParam(name = "birthdayTo", targetNamespace = "http://sst.dk/")
        XMLGregorianCalendar birthdayTo,
        @WebParam(name = "authorizationDateFrom", targetNamespace = "http://sst.dk/")
        XMLGregorianCalendar authorizationDateFrom,
        @WebParam(name = "authorizationDateTo", targetNamespace = "http://sst.dk/")
        XMLGregorianCalendar authorizationDateTo,
        @WebParam(name = "professionGroup", targetNamespace = "http://sst.dk/")
        String professionGroup,
        @WebParam(name = "specialityName", targetNamespace = "http://sst.dk/")
        String specialityName,
        @WebParam(name = "authorizationStatus", targetNamespace = "http://sst.dk/")
        AuthorizationStatus authorizationStatus,
        @WebParam(name = "seventyFiveYearsRule", targetNamespace = "http://sst.dk/")
        SeventyFiveYearsRule seventyFiveYearsRule);

    /**
     * 
     * @param authorizationDateFrom
     * @param professionGroup
     * @param birthdayTo
     * @param specialityName
     * @param authorizationID
     * @param name
     * @param birthdayFrom
     * @param authorizationDateTo
     * @param seventyFiveYearsRule
     * @param authorizationStatus
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetHealthProfessionalsCount", action = "http://sst.dk/GetHealthProfessionalsCount")
    @WebResult(name = "GetHealthProfessionalsCountResult", targetNamespace = "http://sst.dk/")
    @RequestWrapper(localName = "GetHealthProfessionalsCount", targetNamespace = "http://sst.dk/", className = "dk.sst.GetHealthProfessionalsCount")
    @ResponseWrapper(localName = "GetHealthProfessionalsCountResponse", targetNamespace = "http://sst.dk/", className = "dk.sst.GetHealthProfessionalsCountResponse")
    public int getHealthProfessionalsCount(
        @WebParam(name = "name", targetNamespace = "http://sst.dk/")
        String name,
        @WebParam(name = "authorizationID", targetNamespace = "http://sst.dk/")
        String authorizationID,
        @WebParam(name = "birthdayFrom", targetNamespace = "http://sst.dk/")
        XMLGregorianCalendar birthdayFrom,
        @WebParam(name = "birthdayTo", targetNamespace = "http://sst.dk/")
        XMLGregorianCalendar birthdayTo,
        @WebParam(name = "authorizationDateFrom", targetNamespace = "http://sst.dk/")
        XMLGregorianCalendar authorizationDateFrom,
        @WebParam(name = "authorizationDateTo", targetNamespace = "http://sst.dk/")
        XMLGregorianCalendar authorizationDateTo,
        @WebParam(name = "professionGroup", targetNamespace = "http://sst.dk/")
        String professionGroup,
        @WebParam(name = "specialityName", targetNamespace = "http://sst.dk/")
        String specialityName,
        @WebParam(name = "authorizationStatus", targetNamespace = "http://sst.dk/")
        AuthorizationStatus authorizationStatus,
        @WebParam(name = "seventyFiveYearsRule", targetNamespace = "http://sst.dk/")
        SeventyFiveYearsRule seventyFiveYearsRule);

    /**
     * 
     * @param authorizationID
     * @return
     *     returns dk.sst.HealthProfessional
     */
    @WebMethod(operationName = "GetHealthProfessional", action = "http://sst.dk/GetHealthProfessional")
    @WebResult(name = "GetHealthProfessionalResult", targetNamespace = "http://sst.dk/")
    @RequestWrapper(localName = "GetHealthProfessional", targetNamespace = "http://sst.dk/", className = "dk.sst.GetHealthProfessional")
    @ResponseWrapper(localName = "GetHealthProfessionalResponse", targetNamespace = "http://sst.dk/", className = "dk.sst.GetHealthProfessionalResponse")
    public HealthProfessional getHealthProfessional(
        @WebParam(name = "authorizationID", targetNamespace = "http://sst.dk/")
        String authorizationID);

    /**
     * 
     * @param professionCode
     * @return
     *     returns dk.sst.ProfessionGroup
     */
    @WebMethod(operationName = "GetProfessionGroup", action = "http://sst.dk/GetProfessionGroup")
    @WebResult(name = "GetProfessionGroupResult", targetNamespace = "http://sst.dk/")
    @RequestWrapper(localName = "GetProfessionGroup", targetNamespace = "http://sst.dk/", className = "dk.sst.GetProfessionGroup")
    @ResponseWrapper(localName = "GetProfessionGroupResponse", targetNamespace = "http://sst.dk/", className = "dk.sst.GetProfessionGroupResponse")
    public ProfessionGroup getProfessionGroup(
        @WebParam(name = "professionCode", targetNamespace = "http://sst.dk/")
        String professionCode);

    /**
     * 
     * @return
     *     returns dk.sst.ArrayOfProfessionGroup
     */
    @WebMethod(operationName = "GetAllProfessionGroups", action = "http://sst.dk/GetAllProfessionGroups")
    @WebResult(name = "GetAllProfessionGroupsResult", targetNamespace = "http://sst.dk/")
    @RequestWrapper(localName = "GetAllProfessionGroups", targetNamespace = "http://sst.dk/", className = "dk.sst.GetAllProfessionGroups")
    @ResponseWrapper(localName = "GetAllProfessionGroupsResponse", targetNamespace = "http://sst.dk/", className = "dk.sst.GetAllProfessionGroupsResponse")
    public ArrayOfProfessionGroup getAllProfessionGroups();

    /**
     * 
     * @param arrangement
     * @param specialityCode
     * @return
     *     returns dk.sst.Speciality
     */
    @WebMethod(operationName = "GetSpeciality", action = "http://sst.dk/GetSpeciality")
    @WebResult(name = "GetSpecialityResult", targetNamespace = "http://sst.dk/")
    @RequestWrapper(localName = "GetSpeciality", targetNamespace = "http://sst.dk/", className = "dk.sst.GetSpeciality")
    @ResponseWrapper(localName = "GetSpecialityResponse", targetNamespace = "http://sst.dk/", className = "dk.sst.GetSpecialityResponse")
    public Speciality getSpeciality(
        @WebParam(name = "arrangement", targetNamespace = "http://sst.dk/")
        String arrangement,
        @WebParam(name = "specialityCode", targetNamespace = "http://sst.dk/")
        String specialityCode);

    /**
     * 
     * @return
     *     returns dk.sst.ArrayOfSpeciality
     */
    @WebMethod(operationName = "GetAllSpecialities", action = "http://sst.dk/GetAllSpecialities")
    @WebResult(name = "GetAllSpecialitiesResult", targetNamespace = "http://sst.dk/")
    @RequestWrapper(localName = "GetAllSpecialities", targetNamespace = "http://sst.dk/", className = "dk.sst.GetAllSpecialities")
    @ResponseWrapper(localName = "GetAllSpecialitiesResponse", targetNamespace = "http://sst.dk/", className = "dk.sst.GetAllSpecialitiesResponse")
    public ArrayOfSpeciality getAllSpecialities();

}
